### ISSUE TITLE
Menu Development

### ISSUE THREAD

**Issue by Seanp0w** [GPF104/GPF104_Game#100]

**Comment by Seanp0w** [comment]
Started creating a menu

**Comment by Seanp0w** [comment]
Play button and quit button are set to work, Credits, Tutorial and Story have been added

**Comment by Seanp0w** [comment]
Made some sprites for the menu buttons and switched from text to image swap

**Comment by Gard-en** [comment]
Menu looks awesome. When clicking play there was a noticeable delay while the Arena scene loaded. 

Workaround for this was to asynchronously load the game in the background while the menu loaded.

**Comment by Gard-en** [comment]
Further developing on this idea, I've added a splash screen directly following the unity logo, during which the arena scene is loaded. I've tried to time it and code it all in such a way that this loading is as seamless as possible

[video](https://www.youtube.com/watch?v=8-Ug9psqnRM)

**Comment by Seanp0w** [comment]
All that's left is the credits, I'll turn that into a seperate issue.
