### ISSUE TITLE
Double check everything is Ready for another round of playtesting

### ISSUE THREAD

**Issue by Seanp0w** [GPF104/GPF104_Game#113]

**Comment by Gard-en** [comment]
- [ ] Splash Screen Stable
- [ ] Menu Screen Stable
- [ ] Arena Stable
- [ ] Test Build

Here are the steps we need to complete today for a 310723 Play test build.

**Comment by Seanp0w** [comment]
We have updated the Play testing questionaire and sent it off to people

**Comment by Seanp0w** [comment]
^as well as making sure the game had met some requirements of the previous play test build
