### ISSUE TITLE
Animate traps

### ISSUE THREAD

**Issue by Seanp0w** [GPF104/GPF104_Game#116]

**Comment by Seanp0w** [comment]
I have the traps animated, but I need to make it so that their animations start when the player walks within range

**Comment by Seanp0w** [comment]
Idle animation and playerNear bool parameter created

**Comment by Seanp0w** [comment]
Having trouble, Sent to Sam for help

**Comment by Gard-en** [comment]
Animated traps split into two scripts/gameobjects parent and child object.

Parent Object contains boxcollider2D which triggers animation when player enters 'animation' range.
Child object contains circlecollider2D which damages the player.

See: BindiScript.cs for animation
BindiDamage.cs for damage code.

**Comment by Gard-en** [comment]
@Seanp0w If redoing this with #129 - keep in mind the animation state machines.

**Comment by Seanp0w** [comment]
Thanks mate, that's all done
