### ISSUE TITLE
Splash screen start

### ISSUE THREAD

**Issue by Seanp0w** [GPF104/GPF104_Game#118]

**Comment by Seanp0w** [comment]
A playtester has had trouble starting the game, I downloaded the play test and found I had the same issue unless I hit escape

**Comment by Seanp0w** [comment]
The Main Menu buttons don't appear for him after he hits escape for some reason

**Comment by Gard-en** [comment]
Should be fixed now, can we confirm if this has been fixed in latest build?

**Comment by Seanp0w** [comment]
We can. this is done
