### ISSUE TITLE
Boss walk to tower

### ISSUE THREAD

**Issue by Seanp0w** [GPF104/GPF104_Game#121]

**Comment by Gard-en** [comment]
To-do, need to add boss object to game.
Make it spawn when score reaches x

Boss travels towards the tower, when it reaches the tower, it attacks tower
If player is within range, attacks the player.

Tower will need to be given health and healthbar.

**Comment by Gard-en** [comment]
Boss also needs health bar #122

**Comment by Seanp0w** [comment]
took my name off the boss stuff since I didn't really contribute

**Comment by Gard-en** [comment]
Boss walks to tower.
When score is >scorethreshhold then the boss spawns.
There can only be one boss on screen at any one time.

Boss walks toward tower, but stops to attack player when they get too close.
