### ISSUE TITLE
Boss UI

### ISSUE THREAD

**Issue by Gard-en** [GPF104/GPF104_Game#139]

**Comment by Gard-en** [comment]
Placeholder assets for Boss UI is in, which is currently a basic image slider with TMPro text for boss name.


![Image](https://github.com/GPF104/GPF104_Game/assets/34126658/020b2c3a-5971-4082-ab8d-d5e628169396)

**Comment by Seanp0w** [comment]
I posted a boss bar a while back, I'll find it

**Comment by Seanp0w** [comment]
![Image](https://github.com/GPF104/GPF104_Game/assets/136293255/178d2a97-9eea-406f-8bff-3584834d9888)
![Image](https://github.com/GPF104/GPF104_Game/assets/136293255/7db284bc-e8a0-45be-8e43-df9c07f69d22)

**Comment by Seanp0w** [comment]
might be a bit Squid-ee, I'll see what it looks like with Anna's sprites face

**Comment by Seanp0w** [comment]
![Image](https://github.com/GPF104/GPF104_Game/assets/136293255/5bb7454f-728d-412a-9914-38e82b3a3b2b)

**Comment by Seanp0w** [comment]
looks way better

**Comment by Seanp0w** [comment]
I put the bar into the game
