### ISSUE TITLE
Boss Manager

### ISSUE THREAD

**Issue by Gard-en** [GPF104/GPF104_Game#140]

**Comment by Gard-en** [comment]
This code will be responsible for the boss spawning, including interface hooks to show/hide Boss HP Bar.

**Comment by Gard-en** [comment]
Priority

**Comment by Gard-en** [comment]
When score % 1000 == 0
Spawn Boss

**Comment by Gard-en** [comment]
Need to adjust time threshold for boss and score threshold.

**Comment by Seanp0w** [comment]
I adjusted the props so that the boss walks through them, like he's walking through the trees
