### ISSUE TITLE
Finish grass tiles

### ISSUE THREAD

**Issue by pariswilsonn** [GPF104/GPF104_Game#149]
Finish the grass tiles and send them to team to implement into the game

**Comment by pariswilsonn** [comment]
Use a grass tile template for shape guide, design and draw grass tiles for the environment of the game

**Comment by pariswilsonn** [comment]
![Image](https://github.com/GPF104/GPF104_Game/assets/137459134/5333fb42-8a22-420a-9854-a79ed9da65aa)

**Comment by pariswilsonn** [comment]
finished grass tile, I used different shades of green to create dimension and some variety in the grass strokes, and make the pixels represent real grass better

**Comment by Gard-en** [comment]
Changed from designers to developers

Need to implement into unity.

**Comment by pariswilsonn** [comment]
![Image](https://github.com/GPF104/GPF104_Game/assets/137459134/af41a0d6-d3e9-4f02-a99a-5523b8f9508a)


Grass tiles added into the game
