### ISSUE TITLE
Fix the wizard sprite - not working

### ISSUE THREAD

**Issue by pariswilsonn** [GPF104/GPF104_Game#151]
The wizard sprite is not working currently and has been having bleeding issues, this is a big issue so I need to resolve this problem asap.

**Comment by pariswilsonn** [comment]
Animated wizard sprite is having trouble behaving as it should. 


![Image](https://github.com/GPF104/GPF104_Game/assets/137459134/54bb87b3-5910-4823-a01a-9c2de7cc5d5f)

There have been a few issues with the hair bleeding and/or being cut between sprite slices. Sam mentioned a neat little workaround for this might be to separate the hair completely, and we can have the braid simulate physics for some extra level of detail.

I then separated the hair from the wizard and redid the sprite sheet.

![Image](https://github.com/GPF104/GPF104_Game/assets/137459134/29246a10-d4f3-43f6-a976-fbb3dcd48c6e)

The sprite is still having behaviour issues though, so I will need to figure out how to resolve this issue immediately. The size of this sprite is currently 64x64, so I am going to see if changing this helps to fix this problem, otherwise I may need to redo this sprite on another software since I haven't been able to find anything to help this issue on my current software I've been using, this being procreate.

**Comment by Gard-en** [comment]
Redone sprite in game

**Comment by pariswilsonn** [comment]
![Image](https://github.com/GPF104/GPF104_Game/assets/137459134/9c2af0ce-9f37-4db8-80a6-5d9d300921f4)

Fixed wizard sprite. I had to create a new sprite with the same design to get the wizard sprite to work. This wizard still incorporates the same features in the sprite sheet.
