### ISSUE TITLE
Draw 2D comic style wizard for illustration menu

### ISSUE THREAD

**Issue by pariswilsonn** [GPF104/GPF104_Game#152]
Use my pixel style wizard as a reference to create a 2D comic book style version of Slabu the wizard to be used in the illustration menu

**Comment by pariswilsonn** [comment]
![Image](https://github.com/GPF104/GPF104_Game/assets/137459134/b41a3896-18c1-4b31-8757-7f8f189566b1)

**Comment by pariswilsonn** [comment]
Above is the finished comic style version of the wizard, we discussed in our chat that this is the exact vision we were wanting to bring to life for our illustration menu, so we are all happy with this design

**Comment by Seanp0w** [comment]
Great work Paris!
