### ISSUE TITLE
Final touches

### ISSUE THREAD

**Issue by Seanp0w** [GPF104/GPF104_Game#173]

**Comment by Seanp0w** [comment]
Unfortunately I have 12 hours of work tomorrow, so today is the last day I'll be able to sit down and properly work on the game. Sam will also be busy putting together the play test report and finalizing any project management tasks. So we'll be finding things in the game to fix, adjust, add, etc.

**Comment by Seanp0w** [comment]
I'll be typing in what I do today in here, to save time on filling out task after task in the progress tab

**Comment by Seanp0w** [comment]
reduced size of dragon so it gets stuck less

**Comment by Seanp0w** [comment]
I tried getting the props to be destroyed and despawn when the boss ran over them, I couldn't get this to work, but now the boss does walk through the trees, which is nice because he doesnt get stuck and I find is actually suitable thematically

**Comment by Seanp0w** [comment]
Going through the progress tab and closing things off that either won't get done or have been finished

**Comment by Seanp0w** [comment]
Sorting pivot of boss

**Comment by Gard-en** [comment]
Final details are in, most glaring bugs have been fixed. 
I posted a bug test build last night for others in the group to play and help bug test, but so far it's just me and Sean hunting for bugs.

**Comment by Gard-en** [comment]
dONE
