### ISSUE TITLE
Start in bushes

### ISSUE THREAD

**Issue by Seanp0w** [GPF104/GPF104_Game#176]

**Comment by Seanp0w** [comment]
My character just started trapped in some bushes, I need to figure out how to expand out the area where bushes start

**Comment by Gard-en** [comment]
Handled in level generation, if a tile detects 'spawn radius' collider trigger around tower, it doesn't spawn grass tiles, props only spawn on grass tiles

**Comment by Gard-en** [comment]
Object called NoSpawn and can be found under World>NoSpawn in scene hierarchy.

Changed radius from 1 to 1.5
