### ISSUE TITLE
developed Environment - trees and stone walls

### ISSUE THREAD

**Issue by AnnaBorchsheva** [GPF104/GPF104_Game#196]

**Comment by AnnaBorchsheva** [comment]
![image](https://github.com/GPF104/GPF104_Game/assets/136293406/1f9dfc1b-195e-46ec-adec-ed4be8742723)

**Comment by pariswilsonn** [comment]
![Image](https://github.com/GPF104/GPF104_Game/assets/137459134/1b6053bb-f948-4de6-aa36-a333287b1f9a)

single vine sprite option
