### ISSUE TITLE
Edit and organize youtube page

### ISSUE THREAD

**Issue by Seanp0w** [GPF104/GPF104_Game#205]

**Comment by Seanp0w** [comment]
- [x] Banner/profile pics, etc
- [x] Game description
- [x] Price
- [x] Date
- [x] Platform
- [x] All media connected

**Comment by Gard-en** [comment]
YouTube page set up and orgaqnized. Videos uploaded.

**Comment by Gard-en** [comment]
https://www.youtube.com/@SlabuGame
