### ISSUE TITLE
Keyframe Animation - Wizard

### ISSUE THREAD

**Issue by AnnaBorchsheva** [GPF104/GPF104_Game#212]

**Comment by AnnaBorchsheva** [comment]
The draft of keyframe animation.https://github.com/GPF104/GPF104_Game/assets/136293406/1375e81f-c025-46fd-86f3-91ca56e98708

**Comment by AnnaBorchsheva** [comment]
Updated version. https://github.com/GPF104/GPF104_Game/assets/136293406/57d89640-0d00-46cd-8177-cf7d12599133

**Comment by AnnaBorchsheva** [comment]
Colord version https://github.com/GPF104/GPF104_Game/assets/136293406/24515d8c-6d72-4a64-95b0-e438ec90024f

**Comment by Gard-en** [comment]
That's looking awesome!

**Comment by AnnaBorchsheva** [comment]
the enhanced version https://github.com/GPF104/GPF104_Game/assets/136293406/c2ead367-1486-4887-993a-5f865aedd5df
