### ISSUE TITLE
Refine Player Design

### ISSUE THREAD

**Issue by Gard-en** [GPF104/GPF104_Game#24]

**Comment by pariswilsonn** [comment]
Refine the player design to suit mood, aesthetic and concept of the game.

**Comment by AnnaBorchsheva** [comment]
The concept of Sean's wizard was remade by Paris;

- blue-purple
- adding chains
- more detailed wizard's hat

**Comment by Seanp0w** [comment]
The braid was too hard to animate, so we ended up using an updated version of the placeholder

**Comment by pariswilsonn** [comment]
![Image](https://github.com/GPF104/GPF104_Game/assets/137459134/fe94348c-8a27-4744-8fdd-1062e816f2a4)
