### ISSUE TITLE
Start Sound Design

### ISSUE THREAD

**Issue by Gard-en** [GPF104/GPF104_Game#25]

**Comment by Gard-en** [comment]
- Forest sounds
- Ambience
- Spell sounds
- Enemy sounds

**Comment by Gard-en** [comment]
Level ambience achieved using VST3 Omnisphere's extensive sound library. By combining wind sounds with bird chirps, we have a few alternative ambient sounds to give our level some sound immersion.

**Comment by Gard-en** [comment]
Need to experiment with Foley sounds for the different enemy types.

**Comment by Seanp0w** [comment]
Pretty sure Sam is well past started, I'll close this
