### ISSUE TITLE
Develop Enemies

### ISSUE THREAD

**Issue by Gard-en** [GPF104/GPF104_Game#39]

**Comment by Gard-en** [comment]
- [ ] Basic melee enemies
- [ ] Ranged enemies
- [ ] Big damage AOE enemies

Basic enemies should get within melee range of player and damage at random intervals.
Ranged enemies should get within x distance of player and begin shooting.
AOE enemies should get within ranged distance then launch toward the player with a clearly telegraphed/communicated attack.

**Comment by Seanp0w** [comment]
Just need animated sprites
