### ISSUE TITLE
Design Enemies

### ISSUE THREAD

**Issue by Gard-en** [GPF104/GPF104_Game#41]

**Comment by AnnaBorchsheva** [comment]
The amount of enemies is 6 with different strengths.

**Comment by pariswilsonn** [comment]
Each enemy is spawned randomly and have different strengths and abilities. Enemies strength and difficulty in battle may be symbolised through colour.

**Comment by Seanp0w** [comment]
Enemies are in and are final: ghost, wizard, animated dragon
