### ISSUE TITLE
Playtesting

### ISSUE THREAD

**Issue by Gard-en** [GPF104/GPF104_Game#46]

**Comment by Seanp0w** [comment]
We have all contacted friends who are willing to playtest. We might send a playtest survey in with the first assessment to get Dan's feedback. We should also consider using the uni discords new playtest channel

**Comment by Gard-en** [comment]
https://forms.gle/SbWUNdGeewM7VVVX8

**Comment by Gard-en** [comment]
Game builds in spreadsheet: https://docs.google.com/spreadsheets/d/13Df-7T726c2DOapoUvYVR6_drCaZTuhvnWRZuDG_Wdo/edit?usp=sharing

**Comment by Gard-en** [comment]
Manual https://stormgale.dev/public/files/Wizard%20Game%20Manual.pdf

**Comment by Gard-en** [comment]
Start writing a report this week

**Comment by Seanp0w** [comment]
Game has its final build tomorrow, I'll close this
