### ISSUE TITLE
Design Props

### ISSUE THREAD

**Issue by Gard-en** [GPF104/GPF104_Game#51]
- [x] Trees 1-2 variants
- [x] Bushes 1 -3 variants
- [x] Logs -1 - 2 variants
- [x] Rocks - 1 -2 variants
- [ ] Decals (grass, pebbles etc) 5 - 6 variants

**Comment by Gard-en** [comment]
Priority 3

**Comment by pariswilsonn** [comment]
Design props for the environment to show a clear setting and provide a distinctive landscape: Forest

**Comment by Seanp0w** [comment]
We have more than is necessary thanks to Anna and Paris
