### ISSUE TITLE
Scrolls Prefab

### ISSUE THREAD

**Issue by Gard-en** [GPF104/GPF104_Game#58]

**Comment by Gard-en** [comment]
inferno scroll: allow the player the ability to shoot a fireball using right click.

**Comment by Seanp0w** [comment]
as of 11/7: need to have the projectile land at click point, and expand in an "explosion area"

**Comment by Gard-en** [comment]
Inferno object instantiates and travels toward mouse position.
Spawns explosion at destination position which damages enemies.
