### ISSUE TITLE
Melee Enemy

### ISSUE THREAD

**Issue by Seanp0w** [GPF104/GPF104_Game#65]

**Comment by Seanp0w** [comment]
Basic Scripts done weeks ago. Just need animations and play test adjustments

**Comment by Gard-en** [comment]
Lunge functionality in, follows player.
Very basic pathfinding - if distance between vector in last position check hasn't exceeded 0.5 units after 3 seconds, enemy considers itself stuck and 'simulates' physics to fall until it's able to unstuck itself.
