### ISSUE TITLE
Difficulty Scaling

### ISSUE THREAD

**Issue by Seanp0w** [GPF104/GPF104_Game#68]

**Comment by Gard-en** [comment]
#97 
From Playtest feedback: enemies take too long to spawn.

And the game typically ends after 2 minutes and 30 seconds.

**Comment by Gard-en** [comment]
Potential solutions for enemies taking too long to spawn: make bubbles spawn more frequently, and make the arena size smaller.

**Comment by Seanp0w** [comment]
Game has its final build tomorrow, I'll close this
