### ISSUE TITLE
Aesthetic of the game

### ISSUE THREAD

**Issue by AnnaBorchsheva** [GPF104/GPF104_Game#73]

**Comment by AnnaBorchsheva** [comment]
Brainstorming overall idea of the game, style. Sean proposed the idea related to the theme of wizards, witches and other supernatural beings. As a team, we have made the desion to implement it.

**Comment by AnnaBorchsheva** [comment]
At the meeting, artists showed some drafts of the game, where it was added the idea about adding the tower.

![Image](https://github.com/GPF104/GPF104_Game/assets/136293406/bd010a01-c591-483f-8533-f80d3e907a74)

**Comment by AnnaBorchsheva** [comment]
Before the drawing art assets for the game, our idea had been generated by ai to look how it can be represented. ![Image](https://github.com/GPF104/GPF104_Game/assets/136293406/37f1fc06-f603-493a-880a-ca14fff5e9ac)

**Comment by AnnaBorchsheva** [comment]
Overall: pixel art style game inspired dark-fantasy

**Comment by AnnaBorchsheva** [comment]
Finale color pallets of the game: purple, blue, emerald, turquoise, navy. Maybe a bit gloomy.
![Image](https://github.com/GPF104/GPF104_Game/assets/136293406/0c4bd88d-016b-4b80-8457-f4adcac37a26)

![Image](https://github.com/GPF104/GPF104_Game/assets/136293406/0994fae3-fa79-412b-9942-be351dc7532e)

**Comment by AnnaBorchsheva** [comment]
Idea: seperating the enemies and our wizard to make them dusitinguishing by color. The main wizard can be purple, when the enemies will be closer to blue/navy color pallet to help to the player figure out who are enemies.

**Comment by pariswilsonn** [comment]
Define final aesthetic of the game, we set a clear colour palette as seen in the images listed, this consisting of shades of green, blue and purple as our main colours, with hints of yellow for possible detailing.

**Comment by Seanp0w** [comment]
I feel like this was done a while back, so I'll close this
