### ISSUE TITLE
Concepts Enemies

### ISSUE THREAD

**Issue by AnnaBorchsheva** [GPF104/GPF104_Game#75]

**Comment by AnnaBorchsheva** [comment]
Working on "silly enemies",  namely, ghosts and skeletons
![Image](https://github.com/GPF104/GPF104_Game/assets/136293406/9c49fad6-e56f-48a1-b07b-d381b716b885)

**Comment by AnnaBorchsheva** [comment]
Ghosts and skeletons can be melee enemies When they to close to the player, they can attack him/her.

**Comment by AnnaBorchsheva** [comment]
4 July
Concepts of the silly enemies


![Image](https://github.com/GPF104/GPF104_Game/assets/136293406/b823f333-45ad-43c8-ae1d-222152a57df4)



![Image](https://github.com/GPF104/GPF104_Game/assets/136293406/204f9453-43f9-4f55-a26e-188a04e0534a)

**Comment by AnnaBorchsheva** [comment]
4 July
The concept of the possible ranged enemy.

![Image](https://github.com/GPF104/GPF104_Game/assets/136293406/2aca1a63-481b-4847-9706-3a4a4238a3af)

**Comment by AnnaBorchsheva** [comment]
Making the mood board on Pinterest: https://www.pinterest.com.au/ghostannet/asteroid-game/

**Comment by AnnaBorchsheva** [comment]
Some concepts of enemies

![Image](https://github.com/GPF104/GPF104_Game/assets/136293406/f888025f-4ac3-4b58-84b9-ca3d6b1c2469)



![Image](https://github.com/GPF104/GPF104_Game/assets/136293406/ec6fea2d-b3b1-4162-a5b9-25624d814e19)

**Comment by AnnaBorchsheva** [comment]
4 July
Concepts of the silly enemies, the skeleton-warrior and ghost. 


![Image](https://github.com/GPF104/GPF104_Game/assets/136293406/b823f333-45ad-43c8-ae1d-222152a57df4)



![Image](https://github.com/GPF104/GPF104_Game/assets/136293406/204f9453-43f9-4f55-a26e-188a04e0534a)

**Comment by pariswilsonn** [comment]
Enemy Concept - Dragon Sprite

![Image](https://github.com/GPF104/GPF104_Game/assets/137459134/53116b85-9fe4-4b9c-bd1e-0acbbe084f34)

**Comment by AnnaBorchsheva** [comment]
Concept of the "main boss"
![image](https://github.com/GPF104/GPF104_Game/assets/136293406/5062b005-97c6-4272-a13a-707b13beb815)

**Comment by AnnaBorchsheva** [comment]
Concept of the ranged enemy. The chance that it will be in the game is low.
![image](https://github.com/GPF104/GPF104_Game/assets/136293406/cb4a9e68-f877-4217-8b90-b8c0eb5edb7e)
