### ISSUE TITLE
Art assets: Melee Enemies 

### ISSUE THREAD

**Issue by AnnaBorchsheva** [GPF104/GPF104_Game#79]

**Comment by AnnaBorchsheva** [comment]
The colored version of the ghost.
![Image](https://github.com/GPF104/GPF104_Game/assets/136293406/5c680c02-e219-4604-b5b2-43caa5baaeed)

**Comment by AnnaBorchsheva** [comment]
The skeleton design from the top view.
![Image](https://github.com/GPF104/GPF104_Game/assets/136293406/ec35f777-b34f-4b8a-b869-d24f3f445752)

**Comment by AnnaBorchsheva** [comment]
Protypes of skeleton's sprites(b/w)
This enemy is faster than ghosts due to riding horse. When it gets closer too the player it can attack using the sword.

![Image](https://github.com/GPF104/GPF104_Game/assets/136293406/64bc8189-1f68-4197-9dae-43fedbbfc8c1)

**Comment by AnnaBorchsheva** [comment]
The colored version of its sprites.

![Image](https://github.com/GPF104/GPF104_Game/assets/136293406/4505158e-c847-49a5-bd0c-2bc78b453a8d)

**Comment by AnnaBorchsheva** [comment]
working on the sprites of ghost

**Comment by pariswilsonn** [comment]
Dragon enemy sprite


![Image](https://github.com/GPF104/GPF104_Game/assets/137459134/2f98cc7a-24b4-4e67-b691-3b701677d386)

**Comment by AnnaBorchsheva** [comment]
The ghost's sprites in any case.
 ![image](https://github.com/GPF104/GPF104_Game/assets/136293406/831eb38e-f6b7-41d8-b849-0e62a654769b)![image](https://github.com/GPF104/GPF104_Game/assets/136293406/1f4bb6da-3ab9-46b4-beb1-6d1834531b8f)![image](https://github.com/GPF104/GPF104_Game/assets/136293406/dc774c17-ff0f-4f8f-8aa6-971bcc5f4486)

**Comment by pariswilsonn** [comment]
![Image](https://github.com/GPF104/GPF104_Game/assets/137459134/f5ee66e2-0f47-4eff-8c64-4de9346702c6)

Dragon walking sprite

**Comment by pariswilsonn** [comment]
![Image](https://github.com/GPF104/GPF104_Game/assets/137459134/dd384fee-3f31-45cd-83a4-a01e37a9c35d)

Dragon walking with wings flapping animated sprite

**Comment by Seanp0w** [comment]
Thanks guys, I'll close this
