### ISSUE TITLE
Art assets: Ranged Enemies

### ISSUE THREAD

**Issue by AnnaBorchsheva** [GPF104/GPF104_Game#80]

**Comment by AnnaBorchsheva** [comment]
Prototypes of Midnight Touch. His arms are the result of dark magic, which is why it will damage seriously the player. 
![Image](https://github.com/GPF104/GPF104_Game/assets/136293406/56f4725d-5c26-4c04-b421-efa4ae07d818)



![Image](https://github.com/GPF104/GPF104_Game/assets/136293406/488fe9d8-99d6-4511-a7d7-86327f778df9)



![Image](https://github.com/GPF104/GPF104_Game/assets/136293406/80f976f0-8863-455b-9307-f2ca0c804103)

**Comment by AnnaBorchsheva** [comment]
idea: bigger arms? draw rotation of wizard?
goal: add sprites of hands

**Comment by AnnaBorchsheva** [comment]
the concept of the 2d enemy: supernatural being?

**Comment by pariswilsonn** [comment]
Idea: Colour to represent level of difficulty.
Colour discussed: Turquoise/blue/purple

**Comment by pariswilsonn** [comment]
2nd Enemy
Supernatural Being


![Image](https://github.com/GPF104/GPF104_Game/assets/137459134/47b3022e-1047-4f45-82b8-1d5434fc78e9)


Winged supernatural being, holding a fire wand, wearing a golden crown.
Colours may change when symbolic colours are are defined.

**Comment by pariswilsonn** [comment]
2nd Enemy
Supernatural Being



![Image](https://github.com/GPF104/GPF104_Game/assets/137459134/99741572-779c-4023-a550-77983dd9b4a4)

Colour - Red

**Comment by pariswilsonn** [comment]
2nd Enemy 
Supernatural Being

![Image](https://github.com/GPF104/GPF104_Game/assets/137459134/5d4d6199-fa24-436a-bf6f-cd2ef9023a6e)

Colour - Purple

 Colour Options - Turquoise, red, purple

**Comment by Seanp0w** [comment]
All enemies done, I'll close this
