### ISSUE TITLE
Art assets: "Big" Enemies/Boss

### ISSUE THREAD

**Issue by AnnaBorchsheva** [GPF104/GPF104_Game#84]

**Comment by AnnaBorchsheva** [comment]
the first enemy: the unknown hell
the second one: supernatural being inspired by medieval age monsters?

**Comment by AnnaBorchsheva** [comment]
The concept of the hell(not seen from bird view). It's possible that it won't be in the game.
![image](https://github.com/GPF104/GPF104_Game/assets/136293406/93e4aef0-00a6-4083-9948-6fa974a844e2)

**Comment by AnnaBorchsheva** [comment]
Apparently, 2 big enemies will be replaced by one big boss based on Sean's idea to diversify the gameplay. It should be discussed on Friday meeting.

**Comment by AnnaBorchsheva** [comment]
The concept of the new enemy-boss. The temporary name is Tree Beard/Darkwoods.
![image](https://github.com/GPF104/GPF104_Game/assets/136293406/222aff81-205e-4ee0-86a6-3f906e9139e3)

**Comment by Seanp0w** [comment]
Anna has updated the boss with various sprites, I'll close this
