### ISSUE TITLE
Solving the problem of communication

### ISSUE THREAD

**Issue by AnnaBorchsheva** [GPF104/GPF104_Game#88]

**Comment by AnnaBorchsheva** [comment]
It was found the problem of communication. What's the problem? How to solve the issue without conflict(loosing mark)?

**Comment by AnnaBorchsheva** [comment]
the solution:

- [ ] discuss with Sam, project management, what's the problem, how to work with GitHub, why we need it, etc)

- [ ] write the plan of art assets deadline(the weakest point)

**Comment by AnnaBorchsheva** [comment]
The plan of art assets' deadlines
![Image](https://github.com/GPF104/GPF104_Game/assets/136293406/d687cefd-4a2a-45f6-9f78-dc8353baa00d)



![Image](https://github.com/GPF104/GPF104_Game/assets/136293406/e3c6ed75-64b9-49cd-a55b-5345a05d2794)

**Comment by pariswilsonn** [comment]
Discussed more meeting times better suited to everyone in the team.
