### ISSUE TITLE
Implement new main character animated sprite into game

### ISSUE THREAD

**Issue by pariswilsonn** [GPF104/GPF104_Game#89]

**Comment by Gard-en** [comment]
Some issues with sprite clipping, potential workarounds for this might be to separate the braid completely, and make it simulate physics for extra detail.


![Image](https://github.com/GPF104/GPF104_Game/assets/34126658/faa8e6c7-7317-4716-8845-c36ca3fb87e5)


![Image](https://github.com/GPF104/GPF104_Game/assets/34126658/74e3b3f4-9e0f-4a13-b260-5e0479859106)

**Comment by Gard-en** [comment]
Sprite needs to be strictly within the 64x64 grid or (multiple of 32) otherwise we get textures bleeding into different sprite frames.

**Comment by Seanp0w** [comment]
Proved to be too much trouble, this is canned
