### ISSUE TITLE
Produce Concept Art to guide design choice

### ISSUE THREAD

**Issue by Gard-en** [GPF104/GPF104_Game#9]

**Comment by Gard-en** [comment]
Concept art to help guide our game's overall design, feel and aesthetic needs producing. Ideally before we submit the prototype for an early start with asset production.

**Comment by AnnaBorchsheva** [comment]
The draft of the game design:

![Image](https://github.com/GPF104/GPF104_Game/assets/136293406/48700218-e6e5-4ccb-b635-a89daac6a788)

**Comment by pariswilsonn** [comment]
Concept art to guide us toward the direction we want to go with the game. This gives helps us define colour palette, mood, and concept for the game.
