### ISSUE TITLE
Additional Environment Props - Sprites

### ISSUE THREAD

**Issue by pariswilsonn** [GPF104/GPF104_Game#91]

**Comment by pariswilsonn** [comment]
Create additional environment props to incorporate into game.
We discussed more ideas including barbed wire around the castle, as well as vines amongst the castle walls and the wire to give further insight into setting, since our environment is based in the forest

**Comment by Seanp0w** [comment]
Thanks for the extra sprites guys, I'll close this

**Comment by pariswilsonn** [comment]
![Image](https://github.com/GPF104/GPF104_Game/assets/137459134/328c854a-09cc-4f2a-bfcf-d0e01c83dc64)

Vine Sprite
