### ISSUE TITLE
Instruction Illustrations

### ISSUE THREAD

**Issue by pariswilsonn** [GPF104/GPF104_Game#95]
Illustrations of 2D hand drawn art to accompany Instructions. Illustrations will be drawn with a comic art style approach and will not incorporate pixel art for the instruction manual.

**Comment by Seanp0w** [comment]
I did this a while back, Anna suggested it be redone, which I did earlier today, this issue can be closed

**Comment by pariswilsonn** [comment]
These are my character illustrations, in the 2D comic style we all agreed on.

![Image](https://github.com/GPF104/GPF104_Game/assets/137459134/54698aa3-7d85-48e6-8f67-cdd118eda9b0)

Wizard


![Image](https://github.com/GPF104/GPF104_Game/assets/137459134/8ee06d11-d2f1-45f8-abe8-74ebb833261b)

Ghost


![Image](https://github.com/GPF104/GPF104_Game/assets/137459134/d5e09428-5810-4b59-9303-ae934ce68225)

Dragon
