### ISSUE TITLE
UI Design + Refinement

### ISSUE THREAD

**Issue by pariswilsonn** [GPF104/GPF104_Game#96]

**Comment by Seanp0w** [comment]
Started Coming up with different concepts for the layout and Style

![Image](https://github.com/GPF104/GPF104_Game/assets/136293255/981f330a-8221-4358-95d7-7c58da9a182b)
![Image](https://github.com/GPF104/GPF104_Game/assets/136293255/d193a83c-bac4-4d46-90f9-0dacae296711)

**Comment by Seanp0w** [comment]
Finished a placeholder number of scrolls asset, as well as the health bubble, and came up with the idea of having a picture behind the health bubble.

**Comment by Seanp0w** [comment]
UI layout is mostly done, I have just come across a couple of bugs:

1. The menu won't go away at all when playing.

2. Scrolls won't pick up and there is no counter whilst in play mode.

**Comment by Seanp0w** [comment]
No counter fixed, it was a sorting order issue

**Comment by Seanp0w** [comment]
scrolls not being picked up issue sorted. I think it had something to do with the counter not working maybe?

**Comment by Seanp0w** [comment]
Bugs fixed. Now to refine. Also, size the UI to work accordingly with resolution

**Comment by Gard-en** [comment]
The second UI concept on paper you have looks like an excellent idea.

**Comment by Seanp0w** [comment]
![Image](https://github.com/GPF104/GPF104_Game/assets/136293255/3c4dfbd7-d7f3-4e1e-b627-9ec295dfe0f5)

**Comment by Seanp0w** [comment]
Things still to do are:

Boss bar
Mini map
The scroll Icon on the Ui is a bit hard to see, so I'll change that
A "glass covering" for the health to make it look like a crystal ball

Things to refine:

Wall:
Add leaves and realism
Slots for time and score
A "groove" for the hp crystal ball

The buttons are done, but could use a little more polish maybe? Also depends on the title screen background that Anna is working on

**Comment by Seanp0w** [comment]
I've made a boss bar based on Anna's boss assets

**Comment by Seanp0w** [comment]
This is pretty much done except the boss bar, I'll turn that into a seperate issue.
