### ISSUE TITLE
Play Test Game + Gather Feedback

### ISSUE THREAD

**Issue by pariswilsonn** [GPF104/GPF104_Game#97]

**Comment by Seanp0w** [comment]
So something that popped up in the playtesting and something I was personally thinking of as well was a healing mechanic. I'm going to make a potion of healing, but I'm not too sure if it should be randomly spawning or allocated to you after a certain amount of points
it seems people get to around 1200 to 1500 points before dying so maybe 1000 points gets you a potion

**Comment by Seanp0w** [comment]
This should increase longevity of the game as well, it does seem to hit a point where you are likely going to die, our playtesters are dying at almost the exact same time around 2:30

**Comment by Gard-en** [comment]
We could do another spell, in which case we'll need to start thinking about data structures for how to store each scroll. 
We can definitely slate this as an idea.

**Comment by Seanp0w** [comment]
Need to increase the amount of scrolls and potions, decrease the traps

**Comment by Seanp0w** [comment]
Feedback from everyone was super useful and had a massive impact on the turnout of the game
