### ISSUE TITLE
Menu Art Illustration

### ISSUE THREAD

**Issue by pariswilsonn** [GPF104/GPF104_Game#99]
Discuss menu art illustration ideas

**Comment by pariswilsonn** [comment]
We has a group discussion and decided we wanted to create some menu art illustrations. We agreed on a comic book style 2D drawing for this to represent characters from our game

**Comment by AnnaBorchsheva** [comment]
The main artist for illustration for the game was assigned Anna Borshcheva.

**Comment by AnnaBorchsheva** [comment]
Sean' illustration was used as temporary illustration until I send my version.

**Comment by AnnaBorchsheva** [comment]
I created Pinterest folder in Pinterest for inspiration 
https://www.pinterest.com.au/ghostannet/slts-illustration/

**Comment by AnnaBorchsheva** [comment]
I was confused what I should draw, that's why I generated some pictures in Bing and developed them.

**Comment by AnnaBorchsheva** [comment]
The result. I t was animated due Sam.
https://github.com/GPF104/GPF104_Game/assets/136293406/9cc6d265-f723-4306-9c20-e9e702d79856

**Comment by AnnaBorchsheva** [comment]
After disscussion with Sam, I thought it'll be good idea to put in pixel art convertor. Originally, it was planned to draw in pixel art style, but I wanted to use a bigger canvas. 
![SLABU_pixel](https://github.com/GPF104/GPF104_Game/assets/136293406/498476ad-da71-4836-9620-c0413b34f39c)

**Comment by AnnaBorchsheva** [comment]
It was animated and put in the game.
